/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'votes' : bigint,
  'author' : Principal,
  'approved' : boolean,
  'timestamp' : bigint,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'notAttendingCount' : bigint,
  'date' : string,
  'description' : string,
  'rsvpCount' : bigint,
  'location' : string,
}
export interface PrivateUserProfile {
  'displayName' : string,
  'dateOfBirth' : string,
  'socialLinks' : string,
  'onboardingComplete' : boolean,
  'fullName' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
  'registrationComplete' : boolean,
  'profileComplete' : boolean,
  'points' : bigint,
}
export interface PublicProfile {
  'principal' : Principal,
  'displayName' : string,
  'validated' : boolean,
  'socialLinks' : string,
  'biography' : string,
  'eventsAttended' : bigint,
  'website' : string,
  'companyName' : string,
  'servicesOffered' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveMessage' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'countValidatedEvents' : ActorMethod<[Principal], bigint>,
  'createEvent' : ActorMethod<[string, string, string, string], bigint>,
  'createOrUpdatePublicProfile' : ActorMethod<[PublicProfile], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PrivateUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getOwnPublicProfile' : ActorMethod<[], [] | [PublicProfile]>,
  'getPopularEvents' : ActorMethod<[], Array<Event>>,
  'getPublicProfile' : ActorMethod<[Principal], PublicProfile>,
  'getStatistics' : ActorMethod<
    [],
    {
      'totalEvents' : bigint,
      'totalMessages' : bigint,
      'totalUsers' : bigint,
      'totalPoints' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [PrivateUserProfile]>,
  'getVisibleMessages' : ActorMethod<[], Array<ChatMessage>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listPublicProfiles' : ActorMethod<[], Array<PublicProfile>>,
  'listPublicProfilesByValidation' : ActorMethod<
    [boolean],
    Array<PublicProfile>
  >,
  'postMessage' : ActorMethod<[string], bigint>,
  'registerUser' : ActorMethod<[], undefined>,
  'removeMessage' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'rsvpToEvent' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PrivateUserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setProfileValidation' : ActorMethod<[Principal, boolean], undefined>,
  'updateEvent' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'voteMessage' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];