/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'validated' : IDL.Bool,
  'socialLinks' : IDL.Text,
  'biography' : IDL.Text,
  'eventsAttended' : IDL.Nat,
  'website' : IDL.Text,
  'companyName' : IDL.Text,
  'servicesOffered' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'votes' : IDL.Int,
  'author' : IDL.Principal,
  'approved' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const PrivateUserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'socialLinks' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'registrationComplete' : IDL.Bool,
  'profileComplete' : IDL.Bool,
  'points' : IDL.Nat,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notAttendingCount' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'rsvpCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveMessage' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'countValidatedEvents' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrUpdatePublicProfile' : IDL.Func([PublicProfile], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getApprovedMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PrivateUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getOwnPublicProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
  'getPopularEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPublicProfile' : IDL.Func([IDL.Principal], [PublicProfile], ['query']),
  'getStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEvents' : IDL.Nat,
          'totalMessages' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalPoints' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PrivateUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'listPublicProfilesByValidation' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(PublicProfile)],
      ['query'],
    ),
  'postMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'registerUser' : IDL.Func([], [], []),
  'removeMessage' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'rsvpToEvent' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([PrivateUserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setProfileValidation' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'voteMessage' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'validated' : IDL.Bool,
    'socialLinks' : IDL.Text,
    'biography' : IDL.Text,
    'eventsAttended' : IDL.Nat,
    'website' : IDL.Text,
    'companyName' : IDL.Text,
    'servicesOffered' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'votes' : IDL.Int,
    'author' : IDL.Principal,
    'approved' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const PrivateUserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'socialLinks' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'registrationComplete' : IDL.Bool,
    'profileComplete' : IDL.Bool,
    'points' : IDL.Nat,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notAttendingCount' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'rsvpCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveMessage' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'countValidatedEvents' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrUpdatePublicProfile' : IDL.Func([PublicProfile], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getApprovedMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PrivateUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getOwnPublicProfile' : IDL.Func([], [IDL.Opt(PublicProfile)], ['query']),
    'getPopularEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPublicProfile' : IDL.Func([IDL.Principal], [PublicProfile], ['query']),
    'getStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEvents' : IDL.Nat,
            'totalMessages' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalPoints' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PrivateUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listPublicProfiles' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'listPublicProfilesByValidation' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(PublicProfile)],
        ['query'],
      ),
    'postMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'registerUser' : IDL.Func([], [], []),
    'removeMessage' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'rsvpToEvent' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([PrivateUserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setProfileValidation' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'voteMessage' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };